<?xml version="1.0" encoding="utf-8"?><Database Name="QLHS" Class="HocSinhDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-L34EHS5\SQLEXPRESS;Initial Catalog=QLHS;Integrated Security=True" SettingsObjectName="DAO.Properties.Settings" SettingsPropertyName="QLHSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.THAMSO" Member="THAMSOs">
    <Type Name="THAMSO">
      <Column Name="TuoiToiThieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TuoiToiDa" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BANGDIEM" Member="BANGDIEMs">
    <Type Name="BANGDIEM">
      <Column Name="MaBangDiem" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHocSinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaHocKi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaMonHoc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Diem15Phut" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diem1Tiet" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemCuoiKi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Hoc_sinh_BANGDIEM" Member="Hoc_sinh" ThisKey="MaHocSinh" OtherKey="ID" Type="Hoc_sinh" IsForeignKey="true" />
      <Association Name="HOCKI_BANGDIEM" Member="HOCKI" ThisKey="MaHocKi" OtherKey="MaHocKi" Type="HOCKI" IsForeignKey="true" />
      <Association Name="MONHOC_BANGDIEM" Member="MONHOC" ThisKey="MaMonHoc" OtherKey="MaMonHoc" Type="MONHOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BAOCAOTONGKETMON" Member="BAOCAOTONGKETMONs">
    <Type Name="BAOCAOTONGKETMON">
      <Column Name="MaBaoCaoMon" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHocKi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaMon" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SoLuongDatMon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TiLeDatMon" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="DANHSACHLOP_BAOCAOTONGKETMON" Member="DANHSACHLOP" ThisKey="MaLop" OtherKey="MaLop" Type="DANHSACHLOP" IsForeignKey="true" />
      <Association Name="HOCKI_BAOCAOTONGKETMON" Member="HOCKI" ThisKey="MaHocKi" OtherKey="MaHocKi" Type="HOCKI" IsForeignKey="true" />
      <Association Name="MONHOC_BAOCAOTONGKETMON" Member="MONHOC" ThisKey="MaMon" OtherKey="MaMonHoc" Type="MONHOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BAOCAOTONGKETHK" Member="BAOCAOTONGKETHKs">
    <Type Name="BAOCAOTONGKETHK">
      <Column Name="MaBaoCaoHK" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHocKi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SoLuongDat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TiLeDat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="DANHSACHLOP_BAOCAOTONGKETHK" Member="DANHSACHLOP" ThisKey="MaLop" OtherKey="MaLop" Type="DANHSACHLOP" IsForeignKey="true" />
      <Association Name="HOCKI_BAOCAOTONGKETHK" Member="HOCKI" ThisKey="MaHocKi" OtherKey="MaHocKi" Type="HOCKI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETDSLOP" Member="CHITIETDSLOPs">
    <Type Name="CHITIETDSLOP">
      <Column Name="MaChiTietDSLop" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaHocSinh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TBHocKi1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TBHocKi2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="DANHSACHLOP_CHITIETDSLOP" Member="DANHSACHLOP" ThisKey="MaLop" OtherKey="MaLop" Type="DANHSACHLOP" IsForeignKey="true" />
      <Association Name="Hoc_sinh_CHITIETDSLOP" Member="Hoc_sinh" ThisKey="MaHocSinh" OtherKey="ID" Type="Hoc_sinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANHSACHLOP" Member="DANHSACHLOPs">
    <Type Name="DANHSACHLOP">
      <Column Name="MaLop" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SiSo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaKhoiLop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="DANHSACHLOP_BAOCAOTONGKETMON" Member="BAOCAOTONGKETMONs" ThisKey="MaLop" OtherKey="MaLop" Type="BAOCAOTONGKETMON" />
      <Association Name="DANHSACHLOP_BAOCAOTONGKETHK" Member="BAOCAOTONGKETHKs" ThisKey="MaLop" OtherKey="MaLop" Type="BAOCAOTONGKETHK" />
      <Association Name="DANHSACHLOP_CHITIETDSLOP" Member="CHITIETDSLOPs" ThisKey="MaLop" OtherKey="MaLop" Type="CHITIETDSLOP" />
      <Association Name="KHOILOP_DANHSACHLOP" Member="KHOILOP" ThisKey="MaKhoiLop" OtherKey="MaKhoiLop" Type="KHOILOP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Hoc_sinh" Member="Hoc_sinhs">
    <Type Name="Hoc_sinh">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Hoc_sinh_BANGDIEM" Member="BANGDIEMs" ThisKey="ID" OtherKey="MaHocSinh" Type="BANGDIEM" />
      <Association Name="Hoc_sinh_CHITIETDSLOP" Member="CHITIETDSLOPs" ThisKey="ID" OtherKey="MaHocSinh" Type="CHITIETDSLOP" />
    </Type>
  </Table>
  <Table Name="dbo.HOCKI" Member="HOCKIs">
    <Type Name="HOCKI">
      <Column Name="MaHocKi" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHocKi" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="HOCKI_BANGDIEM" Member="BANGDIEMs" ThisKey="MaHocKi" OtherKey="MaHocKi" Type="BANGDIEM" />
      <Association Name="HOCKI_BAOCAOTONGKETMON" Member="BAOCAOTONGKETMONs" ThisKey="MaHocKi" OtherKey="MaHocKi" Type="BAOCAOTONGKETMON" />
      <Association Name="HOCKI_BAOCAOTONGKETHK" Member="BAOCAOTONGKETHKs" ThisKey="MaHocKi" OtherKey="MaHocKi" Type="BAOCAOTONGKETHK" />
    </Type>
  </Table>
  <Table Name="dbo.KHOILOP" Member="KHOILOPs">
    <Type Name="KHOILOP">
      <Column Name="MaKhoiLop" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhoiLop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="KHOILOP_DANHSACHLOP" Member="DANHSACHLOPs" ThisKey="MaKhoiLop" OtherKey="MaKhoiLop" Type="DANHSACHLOP" />
    </Type>
  </Table>
  <Table Name="dbo.MONHOC" Member="MONHOCs">
    <Type Name="MONHOC">
      <Column Name="MaMonHoc" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenMonHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="MONHOC_BANGDIEM" Member="BANGDIEMs" ThisKey="MaMonHoc" OtherKey="MaMonHoc" Type="BANGDIEM" />
      <Association Name="MONHOC_BAOCAOTONGKETMON" Member="BAOCAOTONGKETMONs" ThisKey="MaMonHoc" OtherKey="MaMon" Type="BAOCAOTONGKETMON" />
    </Type>
  </Table>
  <Function Name="dbo.AddHK" Method="AddHK">
    <Parameter Name="mahk" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenhk" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaHS" Method="XoaHS">
    <Parameter Name="MaHS" Parameter="maHS" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TracuuhocsinhKL" Method="TracuuhocsinhKL">
    <Parameter Name="MaK" Parameter="maK" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="TracuuhocsinhKLResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TBHocKi1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TBHocKi2" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TracuuhocsinhLop" Method="TracuuhocsinhLop">
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="TracuuhocsinhLopResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TBHocKi1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TBHocKi2" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.updateHS" Method="updateHS">
    <Parameter Name="TenL" Parameter="tenL" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="MaHS" Parameter="maHS" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="address" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mail" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="date" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="sex" Type="System.String" DbType="NChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AddMH" Method="AddMH">
    <Parameter Name="mamh" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="tenmh" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.noneHK" Method="noneHK">
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="noneHKResult">
      <Column Name="MaMonHoc" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenMonHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.haveHK" Method="haveHK">
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="haveHKResult">
      <Column Name="MaMonHoc" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenMonHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaBaoCaoMon" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaHocKi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaMon" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SoLuongDatMon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TiLeDatMon" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.mhtoclass" Method="mhtoclass">
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Mamh" Parameter="mamh" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="maHK" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateD" Method="updateD">
    <Parameter Name="MaHS" Parameter="maHS" Type="System.Int32" DbType="Int" />
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="p15" Type="System.Double" DbType="Float" />
    <Parameter Name="t1" Type="System.Double" DbType="Float" />
    <Parameter Name="ck" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.bang" Method="bang">
    <ElementType Name="bangResult">
      <Column Name="MaChiTietDSLop" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaHocSinh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TBHocKi1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TBHocKi2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaMonHoc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Diem15Phut" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diem1Tiet" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemCuoiKi" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.updateSL" Method="updateSL">
    <Parameter Name="malop" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="mamh" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateTL" Method="updateTL">
    <Parameter Name="malop" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="mamh" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="tl" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AddMHtoNH" Method="AddMHtoNH">
    <Parameter Name="mabc" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="mahk" Type="System.Int32" DbType="Int" />
    <Parameter Name="mamh" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.setup" Method="setup">
    <Parameter Name="malop" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="mamh" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.KTave" Method="KTave">
    <Parameter Name="Malop" Parameter="malop" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="MaHK" Parameter="maHK" Type="System.Int32" DbType="Int" />
    <ElementType Name="KTaveResult">
      <Column Name="MaBangDiem" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaHocSinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaHocKi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaMonHoc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Diem15Phut" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diem1Tiet" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemCuoiKi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaChiTietDSLop" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaHocSinh1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TBHocKi1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TBHocKi2" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ktclass" Method="ktclass">
    <Parameter Name="Malop" Parameter="malop" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="MaHK" Parameter="maHK" Type="System.Int32" DbType="Int" />
    <ElementType Name="ktclassResult">
      <Column Name="MaHocSinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.addBCHK" Method="addBCHK">
    <Parameter Name="MabcHK" Parameter="mabcHK" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="MaHK" Parameter="maHK" Type="System.Int32" DbType="Int" />
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="SL" Parameter="sL" Type="System.Int32" DbType="Int" />
    <Parameter Name="TL" Parameter="tL" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TONGKET" Method="TONGKET">
    <ElementType Name="TONGKETResult">
      <Column Name="MaHocKi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>